name: sigaa_notas
description: Automatiza a visualização de notas no site do SIGAA do CEFET/MG.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.22+33

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+3
  html: ^0.14.0+3
  flutter_launcher_icons: ^0.7.4
  dynamic_theme: ^1.0.1
  quiver: ^2.1.2+1
  oktoast: ^2.3.0
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  path: ^1.6.4
  device_calendar: ^1.0.0+2
  url_launcher: ^5.4.1
  sprintf: ^4.0.2
  quick_actions: ^0.4.0+1
  pull_to_refresh: ^1.5.7
  package_info: ^0.4.0+13
  dapackages: ^1.1.1
  
# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
